# Generated by Django 5.1.7 on 2025-03-23 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aynage_app', '0003_vacancy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('tech', 'Technology'), ('fashion', 'Fashion'), ('help', 'Help'), ('ngo', 'NGO')], max_length=50)),
                ('description', models.TextField()),
                ('status', models.IntegerField(choices=[(1, 'Published'), (0, 'Unpublished')], default=0)),
                ('banner', models.ImageField(blank=True, null=True, upload_to='blog_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
