# Generated by Django 5.1.7 on 2025-03-23 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aynage_app', '0004_blog_delete_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='status',
            field=models.CharField(choices=[('Published', 'Published'), ('Published', 'Unpublished')], default='Unpublished', max_length=50),
        ),
    ]
