# Generated by Django 5.1.7 on 2025-03-23 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aynage_app', '0005_alter_blog_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='status',
            field=models.IntegerField(choices=[(1, 'Published'), (0, 'Unpublished')], default=0),
        ),
    ]
