# Generated by Django 5.2.13 on 2026-05-01 19:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aynage_app', '0016_blog_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blogs_added', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='blog',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blogs_updated', to=settings.AUTH_USER_MODEL),
        ),
    ]
